services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/shell-l33t:cached
      - shell-l33t-uv-cache:/home/vscode/.cache/uv
      - ${HOME}/.claude:/home/vscode/.claude:cached
      - ${HOME}/.claude.json:/home/vscode/.claude.json:cached
      - ${HOME}/.deepagents:/home/vscode/.deepagents:cached
    env_file:
      - .env

    command: sleep infinity



volumes:
  shell-l33t-uv-cache:

